version: "3.9"
services:
  server:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    hostname: server
    volumes:
      - /usr/src/app/node_modules
    networks:
      - internal
    ports:
      - 8080:8080
    env_file:
      ./backend/.env.local

  webclient:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - /usr/src/app/node_modules
    ports:
      - 80:80
    env_file:
      ./frontend/.env.local
    networks:
      - internal

networks:
  internal:
    driver: bridge