spring:
  datasource:
    url: jdbc:h2:file:./database/backend;AUTO_SERVER=TRUE;MODE=MySQL;NON_KEYWORDS=USER
    username: admin
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  h2:
    console.enabled: true
    console.path: /h2-console
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: abee8ba24898a4e6fd58
            client-secret: 958218d36a6a1c85f70b04f57b4bc05afffc861f