name: CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npm run nx:workspace-lint
      
      - name: Lint
        run: npm run nx:lint

      - name: Test
        run: npm run nx:test

      - name: Build
        run: npm run nx:build

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: '@semantic-release-bot'
        run: npm run semantic-release
